### ISSUE TITLE
Wrong precedence for prime operator

### ISSUE THREAD

**Issue by craft095** [tlaplus-community/tree-sitter-tlaplus#84]
Hello,

tree-sitter parses following expressions incorrectly:
`[] y'` produces `([] y)'` expected `[] (y')`
`<> y'` produces `(<> y)'` expected `<> (y')`
`ENABLED y'` produces `(ENABLED y)'` expected `ENABLED (y')`
`UNCHANGED y'` produces `(UNCHANGED y)'` expected `UNCHANGED (y')`

Interestingly, following is parsed correctly
`-y'` produces `-(y')`
`~y'` produces `~(y')`
`DOMAIN y'` produces `DOMAIN (y')`
`SUBSET y'` produces `SUBSET (y')`
`UNION y'` produces `UNION (y')`

Thanks for the great library!

**Comment by ahelwer** [comment]
Thanks for the report! I will look into this some time next week. @will62794 for FYI

**Comment by ahelwer** [comment]
@craft095 can you double check that SANY parses these as you state are correct instead of giving you a parse error? TLA+ takes an idiosyncratic approach to operator precedence where operators have precedence ranges, and if the range of two operators overlap it's a parse error for them to not be disambiguated with parentheses.

**Comment by craft095** [comment]
@ahelwer You are right: those indeed result in parse errors. I created a bunch of test cases for my TLA+ style checking tool, and some of these tests happened to be syntactically incorrect. Sorry about that.
Thank you!
